### ISSUE TITLE
[Feature] Method to stop ship movement

### ISSUE THREAD

**Issue by karnthis** [pecko95/EarthDefense#12]
Currently there is no way to stop the ship from moving unless you hit a game edge. Ideally there would be a way to stop the ship, either by stopping on end keypress or an additional hotkey.

This can be either stand alone or incorporated in issue #3

**Comment by pstevovski** [comment]
Updated ship movement to be per key pressed / hold, rather than key pressed setting a direction and that way moving the ship all the time. Commit: [d798620](https://github.com/pecko95/EarthDefense/commit/d7986203c68870af3da73aee7d6e2d647396bb9c#diff-93471d4bf84d0569fadcebe5fba72773R269)
