### ISSUE TITLE
[Feature] Refactor ship movement 

### ISSUE THREAD

**Issue by nartc** [pecko95/EarthDefense#3]

**Comment by pstevovski** [comment]
Changed the way the ship moves by adding support for multiple keys pressed at once. Ship is not moving all the time now, it only moves when key(s) is pressed & hold. Commit: [d798620](https://github.com/pecko95/EarthDefense/commit/d7986203c68870af3da73aee7d6e2d647396bb9c#diff-93471d4bf84d0569fadcebe5fba72773R269)
