### ISSUE TITLE
[Bug] Score math multiplier adding to base

### ISSUE THREAD

**Issue by karnthis** [pecko95/EarthDefense#7]
Not sure how this is intended to function, but score seems to be taking the base score and adding the multiplier result to it. If that is intended, why have the base score?

![funnymath](https://user-images.githubusercontent.com/27795776/47876939-9ebae600-dde8-11e8-92f8-63c766923227.png)

**Comment by pstevovski** [comment]
Removed score from displaying. Each kill when game is ended is multiplied by 100 and that is the score (score = killCount * 100) that will be then multiplied by the.. multiplier :P resulting in a finalScore = score + (score * multiplier). Commit: [668b24a](https://github.com/pecko95/EarthDefense/commit/668b24aa6cf4e9eb779b5dc1218a2ebb96cc6768)
