### ISSUE TITLE
[Feature] Button presses stop canceling each other

### ISSUE THREAD

**Issue by karnthis** [pecko95/EarthDefense#9]
Current behavior is a button press is registered and continues for the time held down **unless** a second button is pressed. This second button completely cancels the previous press.

Proposal - One of the following:
- New presses override previous press, when released previous press is resumed
- Support multiple concurrent button presses **(Preferred)**

**Comment by pstevovski** [comment]
Added support for multiple keys pressed at once. Commit: [d798620](https://github.com/pecko95/EarthDefense/commit/d7986203c68870af3da73aee7d6e2d647396bb9c#diff-93471d4bf84d0569fadcebe5fba72773R269)
